feature: #239 - Implement automatic log sending in case deployment failure.

diff --git a/.github/workflows/cd_backend_java_parcer.yml b/.github/workflows/cd_backend_java_parcer.yml
--- a/.github/workflows/cd_backend_java_parcer.yml
+++ b/.github/workflows/cd_backend_java_parcer.yml
@@ -49,11 +49,11 @@ jobs:
             cd "$REPO_DIR"
 
             # get the latest changes
+            git clean -fdx
+            git reset --hard "$TAG_SHA"
             git fetch --all --prune
             git checkout -B "$BRANCH" "$TAG_SHA"
-            git reset --hard "$TAG_SHA"
             git pull origin "$BRANCH"
-            git clean -fdx
 
             # go to the code directory  
             cd "$REPO_DIR/frontend"
@@ -96,60 +96,20 @@ jobs:
 
             # checking container status.
             if [ "$(docker inspect -f {{.State.Running}} $CONTAINER_ID)" != "true" ] || [ "$(docker inspect -f {{.State.Restarting}} $CONTAINER_ID)" = "true" ] ; then
-                echo "Container failed to start. Capturing logs..." >&2
+                echo " "
+                echo " "
+                echo " "
+                echo " "
+                echo " "
+                echo "!!!!!!!!! Container failed to start. Capturing logs... !!!!!!!!" >&2
                 # getting last log strings.
-                LOGS=$(docker logs --tail 50 $CONTAINER_ID 2>&1)
-                # LOGS=$(docker logs --tail 50 $CONTAINER_ID 2>&1 | base64)
-                docker logs --tail 50 $CONTAINER_ID 2>&1
-                
-                # creating output variable 'container_logs' with logs content and transfer to github actions output
-                # v1
-                # echo "::set-output name=container_logs::string from previous job" # old method
-                # v2
-                echo "container_logs=string from previous job 222" >> $GITHUB_OUTPUT
-                # v3
-                # echo "container_logs<<EOF" >> $GITHUB_OUTPUT
-                # echo "$LOGS" >> $GITHUB_OUTPUT
-                # echo "EOF" >> $GITHUB_OUTPUT
-                
+                docker logs --tail 100 $CONTAINER_ID 2>&1
+            
                 # exiting with failure, so all job ends with failure.
                 exit 1 
             fi
 
-      - name: Set logs output for failed run
-        id: set_logs_output
-        if: failure()
-        run: |
-          LOGS_FROM_SSH="${{ steps.deploy_and_check.outputs.stdout }}"
-          echo "container_logs<<EOF" >> $GITHUB_OUTPUT
-          echo "$LOGS_FROM_SSH" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
 
-  print_on_failure:
-    runs-on: ubuntu-latest
-    needs: build_and_deploy
-    if: failure()
-    steps:
-      - name: print logs
-        run: |
-          echo "LOGS:"
-          echo "1 - ${{ needs.build_and_deploy.outputs.container_logs }}"
-          echo "2 - ${{ needs.build_and_deploy.outputs.stdout }}"
-          echo "3 - ${{ job.build_and_deploy.steps.deploy_and_check.outputs.container_logs }}"
-          echo "4 - ${{ job.build_and_deploy.steps.deploy_and_check.outputs.stdout }}"
-          echo "5 - ${{ needs.build_and_deploy.outputs.step_container_logs }}"
-          echo "6 - ${{ needs.build_and_deploy.outputs.step_stdout }}"
-          echo "7 - ${{ job.build_and_deploy.steps.deploy_and_check.outputs.step_container_logs }}"
-          echo "8 - ${{ job.build_and_deploy.steps.deploy_and_check.outputs.step_stdout }}"
-          echo "9 - $container_logs"
-          echo "10 - $stdout"
-          echo "11 - $step_container_logs"
-          echo "12 - $step_stdout"
-        env:
-          container_logs: ${{ needs.build_and_deploy.outputs.container_logs }}
-          stdout: ${{ needs.build_and_deploy.outputs.stdout }}
-          step_container_logs: ${{ job.build_and_deploy.steps.deploy_and_check.outputs.container_logs }}
-          step_stdout: ${{ job.build_and_deploy.steps.deploy_and_check.outputs.stdout }}
 
   notify_on_failure:
     runs-on: ubuntu-latest
@@ -168,18 +128,7 @@ jobs:
             **Repo**: `${{ github.repository }}`
             **Branch**: `${{ github.ref_name }}`
             **Commit**: `${{ github.sha }}`
-            **Deploy log**: `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
-            
-            \`\`\`
-            **LOGS:**
-            ${{ needs.build_and_deploy.outputs.container_logs }}
-            `${{ needs.build_and_deploy.outputs.container_logs }}`
-            ${{ job.build_and_deploy.steps.deploy_and_check.outputs.container_logs }}
-            `${{ job.build_and_deploy.steps.deploy_and_check.outputs.container_logs }}`
-            ${{ needs.build_and_deploy.outputs.stdout }}
-            `${{ needs.build_and_deploy.outputs.stdout }}'
-            ${{ job.build_and_deploy.steps.deploy_and_check.outputs.stdout }}
-            `${{ job.build_and_deploy.steps.deploy_and_check.outputs.stdout }}`
-
-            \`\`\`
+            **Run ID**: `${{ github.run_id }}`
+            **Deploy log link address**: `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
+            **Deploy log direct link**: [LOGS](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
 
