feature: #239 - Implement automatic log sending in case deployment failure. fix log collection

diff --git a/.github/workflows/cd_backend_java_parcer.yml b/.github/workflows/cd_backend_java_parcer.yml
--- a/.github/workflows/cd_backend_java_parcer.yml
+++ b/.github/workflows/cd_backend_java_parcer.yml
@@ -87,6 +87,10 @@ jobs:
             # wait few seconds, until container is run
             sleep 20
 
+      - name: Check container status and get logs
+        id: check_status
+        run: |
+        
             # get container id of the just started container
             CONTAINER=$(ENV=dev && ENV=$ENV docker compose --env-file .env --env-file .env."$ENV" ps -q back-java-parser)
 
@@ -97,9 +101,12 @@ jobs:
                 LOGS=$(docker logs --tail 50 $CONTAINER 2>&1)
                 
                 # creating output variable 'container_logs' with logs content and transfer to github actions output
-                echo "::set-output name=container_logs::$LOGS"
-                
-                exit 1 # exiting with failure, so all job ends with failure.
+                #echo "::set-output name=container_logs::$LOGS"
+                echo "container_logs<<EOF" >> $GITHUB_OUTPUT
+                echo "$LOGS" >> $GITHUB_OUTPUT
+                echo "EOF" >> $GITHUB_OUTPUT
+                # exiting with failure, so all job ends with failure.
+                exit 1 
             fi
   
   notify_on_failure:
