Update validators

diff --git a/.github/workflows/validate_branch_name.yml b/.github/workflows/validate_branch_name.yml
--- a/.github/workflows/validate_branch_name.yml
+++ b/.github/workflows/validate_branch_name.yml
@@ -13,9 +13,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set script permissions
-        run: chmod +x ./.github/scripts/validate-branch-name.sh
-
       - name: Get branch name
         id: get_branch
         run: |
@@ -24,6 +21,36 @@ jobs:
           else
             BRANCH_NAME=${GITHUB_REF#refs/heads/}
           fi
+          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
 
-      - name: Validate Branch Name
-        run: ./.github/scripts/validate-branch-name.sh ${{ steps.get_branch.outputs.branch }}
+      - name: Validate branch name
+        id: validate_branch_name
+        run: |
+          echo "BRANCH_NAME=$BRANCH_NAME"
+          if [[ "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|refactor|test|docs|chore)\/[0-9]+-[a-z0-9-]{5,}$ ]]; then
+            echo "Branch name '$BRANCH_NAME' is valid."
+            exit 0 
+          else
+            echo "Branch name '$BRANCH_NAME' is invalid. It must match the pattern: <type>/<issue-id>-<short-description>"
+            echo "Available <type>: feature|bugfix|hotfix|refactor|test|docs|chore"
+            exit 1 
+          fi
+        env: 
+          BRANCH_NAME: ${{ env.BRANCH_NAME }}
+
+      - name: Validate commit messages
+        run: |
+          COMMIT_MESSAGES=$(git log origin/${{ github.event.before }}..HEAD --pretty=format:"%s")
+          echo "$COMMIT_MESSAGES" | while read -r message; do
+            if [[ ! "$message" =~ ^(feature|bugfix|hotfix|refactor|test|docs):\ #[0-9]+\ .{1,72} ]]; then
+              echo "Commit message '$message' does not follow the naming convention."
+              echo "Expected format: <type>: #<issue-id> <short summary>"
+              exit 1
+            fi
+            FIRST_LINE=$(echo "$message" | head -n 1)
+            if [ ${#FIRST_LINE} -gt 72 ]; then
+              echo "First line of commit message '$FIRST_LINE' exceeds 72 characters."
+              exit 1
+            fi
+          done
+
